version: '2.3'

services:
  ntfy:
    image: ntfy
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "serve"
    environment:
      - TZ=Asia/Kuala_Lumpur
    # ports:
    #   - "8083:80"
    volumes:
      - /opt/DATA/ntfy/cache:/var/cache/ntfy
      - /opt/DATA/ntfy/etc:/etc/ntfy
    restart: unless-stopped

# volumes:
#   cache:
#   etc:

networks:
  default:
    external: true
    name: default_net