version: '3.8'

# Wordpress compose file
services:
  db:
    image: mariadb:11.1.2-jammy
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  web:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
#    image: wordpress:latest
#    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8282:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 0
      WORDPRESS_LOG_LEVEL: warning
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', true);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_MAX_MEMORY_LIMIT', '256M');
        define('WP_POST_REVISIONS', 5);
        define('WP_REDIS_HOST', 'redis');
        define('WP_REDIS_PORT', 6379);
        define('WP_REDIS_DB', 0);
        define('WP_REDIS_PASSWORD', '');
        define('WP_REDIS_PREFIX', 'wp_');
        define('WP_REDIS_SENTINEL_MODE', false);
        define('WP_REDIS_SENTINEL_PERSISTENT_ID', '');
        define('WP_REDIS_SENTINEL_MASTER_NAME', '');
        define('WP_REDIS_SENTINEL_MASTER_HOST', '');
        define('WP_REDIS_SENTINEL_MASTER_PORT', '');
        define('WP_REDIS_SENTINEL_MASTER_PASSWORD', '');
        define('WP_REDIS_SENTINEL_SENTINEL', false);
        define('WP_REDIS_SENTINEL_PORT', 0);

volumes:
  db_data:
  wordpress_data:

