FROM varnish:latest 
ENV VARNISH_SIZE 256M

# set the user to root, and install build deps 
USER root
RUN set -e; \
    apt-get update && apt-get install -y build-essential apt-transport-https curl && \
    curl -L 
# apt -y install $VMOD_DEPS /pkgs/*.deb; \
# install one, possibly multiple vmods
install-vmod https://github.com/varnish/varnish-modules/releases/download/0.22.0/varnish-modules-0.22.0.tar.gz \
    # clean up
    && apt-get purge -y --auto-remove build-essential && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

USER varnish