# Nginx Proxy Manager

version: '3.8'
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - /opt/DATA/nginx-proxy-manager/data:/data
      - /opt/DATA/letsencrypt/etc:/etc/letsencrypt
networks:
  default:
    external: true
    name: default_net

# default_net needs to be created separately, before running this compose file.
# Use: docker network create default_net
