version: '3.8'

services:
  db:
    image: mysql
    restart: always
    volumes:
      - /opt/DATA/mysql/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wpuser
      MYSQL_ROOT_PASSWORD: dbrootpassword

  web:
    build: ./wordpress
    image: wordpress
    restart: always
    volumes:
      - /opt/DATA/wordpress/html:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wpuser
      WORDPRESS_DB_NAME: wpdb
    depends_on:
      - db

  cache:
    build:
      context: ./varnish
      dockerfile: ./Dockerfile-varnish
    image: varnish
    volumes:
      - /opt/DATA/varnish/etc/varnish.vcl:/etc/varnish/default.vcl
    restart: always
    depends_on:
      - web

  proxy:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - /opt/DATA/nginx-proxy-manager/data:/data
      - /opt/DATA/letsencrypt/etc:/etc/letsencrypt
    depends_on:
      - cache

networks:
  default:
    external: true
    name: default_net
